// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Configuration struct {
	ChainID    string `json:"chainId"`
	Denom      string `json:"denom"`
	Prefix     string `json:"prefix"`
	AmountSend int64  `json:"amountSend"`
	FeeAmount  int64  `json:"feeAmount"`
	Memo       string `json:"memo"`
	GasLimit   uint64 `json:"gasLimit"`
}

type SendInput struct {
	ToAddress string `json:"toAddress"`
}

type TxResponse struct {
	// Corresponding to the transaction hash.
	Hash string `json:"hash"`
	// Return the result code of transaction.
	// See code correspondence error : https://github.com/cosmos/cosmos-sdk/blob/main/types/errors/errors.go
	Code int `json:"code"`
	// Description of error if available.
	RawLog    *string `json:"rawLog"`
	GasWanted int64   `json:"gasWanted"`
	GasUsed   int64   `json:"gasUsed"`
}
